version: "2"

services:
  database:
    container_name: blog-database
    build:
      context: ./database
    environment:
      - "TZ=Asia/Seoul"
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - ./database/docker/data:/var/lib/mysql
    ports:
      - "3306:3306"

  app:
    container_name: blog-app
    build: ./app
    environment:
      - DATABASE_HOST=database
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    links:
      - database
    ports:
      - "80:3000"
