name: Deploy blog server

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build jobs
    runs-on: ubuntu-latest

    steps:
      - name: Test job
        run: |
          ssh pys99py@13.209.8.104
