name: Deploy blog server

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build jobs
    runs-on: ubuntu-latest

    steps:
      - name: Test job
        run: |
          export DOCKER_HOST=tcp://13.209.8.104:2376
          docker ps
