name: Deploy blog server

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build jobs
    runs-on: ubuntu-latest

    steps:
      - name: Test job
        run: |
          ssh ${{secrets.EC2_USER}}@${{secrets.EC2_HOST}}
